//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Win171108_EFKategoriUrunProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        public int UrunID { get; set; }
        public string UrunAdi { get; set; }
        public Nullable<int> Miktar { get; set; }
        public Nullable<int> KatID { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
    }
}
